### ISSUE TITLE
User deletion disowned comments when the checkbox wasn't set

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#1004]
A user deleted their account [without checking 'disown'](https://lobste.rs/s/zp4ofg/lobster_burntsushi_has_left_site#c_ot2yb7) and all their comments were disowned anyways. My guess without reading the code is that `0` is incorrectly coerced to a truthy value, given we're probably reading this value without using Rails's code for assigning form inputs to model attributes.

**Comment by pushcx** [comment]
Worth checking that the "I'm sure" checkbox is working properly, too. Maybe it's been coerced to 'true' as well.

**Comment by itsliamegan** [comment]
Looks like the relevant line is [here](https://github.com/lobsters/lobsters/blob/19ff715102238b1bfb1430be624724eba7c95a80/app/controllers/settings_controller.rb#L24). Since Rails creates a hidden input to submit when the checkbox isn't checked, `params[:user][:disown]` is always `"0"` or `"1"`, which are both `present?` and thus the condition is always true. The same goes for [this check](https://github.com/lobsters/lobsters/blob/19ff715102238b1bfb1430be624724eba7c95a80/app/controllers/settings_controller.rb#L13) of `params[:user][:i_am_sure]`

**Comment by pushcx** [comment]
Looks like the bug was introduced in 089f3475baab90341021c77e628da964545b602f. We changed from using`check_box_tag` to `check_box`, which has a [gotcha](https://api.rubyonrails.org/classes/ActionView/Helpers/FormBuilder.html#method-i-check_box-label-Gotcha).

Let's fix this by checking for 0 or 1 in the controller, and audit the entire commit to see if we picked up other bugs due to this gotcha.

**Comment by briankung** [comment]
Well, that's scary. I just got my lobsters dev environment up and running again and discovered that, yep, you don't have to click "I am sure" in order to delete your account. Good thing I didn't test that with my live account 😂

**Comment by pushcx** [comment]
Fixed in #1010 by @briankung.
