### ISSUE TITLE
Lobste.rs down

### ISSUE THREAD

**Issue by timvisee** [lobsters/lobsters#1016]
It seems that [lobste.rs](https://lobste.rs/) is down.

When can we expect to get it back online?

A random down-detection website confirms this as well: https://www.isitdownrightnow.com/lobste.rs.html

**Comment by timvisee** [comment]
Seems to be up again!

**Comment by pushcx** [comment]
Digital Ocean powered off our VPS for emergency maintenance. It's unclear what was wrong, their email contained several errors and omissions. It sounds like there was a hardware issue. It's unclear why they didn't power the VPS back on after migrating so that we could've had 5 minutes of downtime instead of 5 hours. I'm in touch for more information but not optimistic.
