### ISSUE TITLE
Can't delete system messages

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#1049]
When a Story is edited by user suggestions, the submitter gets a Message. That Message gets an `author_user_id` of `0` and appears in the inbox as being from _System_ rather than a named user.

Since 12644b271 (and triggered by a user for the first time last month after >3y!) a bug prevents deleting these Messages, individually or batch-delete. When a recipient deletes a message it toggles the `deleted_by_recipient` boolean and saves, whereupon a callback (arrrgggggh) checks to see if the record should be deleted from the database. But instead an exception is thrown by `.save!` because the object is invalid without a real `author_user_id`.

This needs a fix so users can delete system messages. Maybe the right fix is to make `author_user_id` nullable and migrate to replace the `0`s with `NULL`s? Or maybe `MessagesController#destroy` and `#batch_delete` should just directly delete records when possible and delete the `check_for_both_deleted` magic entirely?

**Comment by mrtorks** [comment]
Hi @pushcx 
Interesting bug.

I do agree with using setting records with `NULL` instead of `0` and then check for a null condition with an override to delete the record.
Directly deleting the record through
`MessagesController#destroy` and `#batch_delete` is also a great idea however in my opinion, implementing that might introduce complexity. 

If possible more details about the bug could help me develop a more concrete solution.

**Comment by pushcx** [comment]
What details would be useful to you? After I figured out what caused the exception I wrote this up to give as much context as possible, so I don't know what more would help or I would've already included it. :)

**Comment by mrtorks** [comment]
Pardon my dust @pushcx my thought process ran wild and it was late when I was responding. Using the null option definitely works. You could give that a try to see where it goes.

**Comment by vincentrolfs** [comment]
I'm on it :)

**Comment by vincentrolfs** [comment]
I created PR #1078
