### ISSUE TITLE
Seeing instance of "Story removed by moderator but no log message was found."

### ISSUE THREAD

**Issue by jameslittle230** [lobsters/lobsters#1069]
Hi! I was cruising through the modlog, clicking some links, and landed on the following URL:

https://lobste.rs/s/qkviu8/how_we_ship_github_mobile_every_week

The content on the page reads:

> Story removed by moderator but no log message was found. Please report this bug.

So here I am, reporting the bug. The removal definitely has a log message - I can see it in the modlog, it just doesn't show up on the detail page.

I'm logged in as a non-mod non-admin user; when I open the URL in an incognito window the page content changes to, simply, `Story was removed.`

Happy to provide any other details that help :)

**Comment by pushcx** [comment]
Ha, I checked the full db, fixed the two stories missing log messages, and wrote that anyways as "can't happen" code. I guess you can never be too cautious. Thanks for reporting this. This is a data modeling issue: at the moment the 404 page finds the modlog message  _starting_ `deleted story`, but since #1034 there might also be attributes changed in front of that.
