### ISSUE TITLE
A css #ID is used twice.

### ISSUE THREAD

**Issue by ymeynot45** [lobsters/lobsters#1097]
On the account settings page you use `#user_password` twice.
For the New Password input & the Verify Password input on the delete account section.

**Comment by johnpash** [comment]
I've done a fix here #1155 which adds a [form namespace](https://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-form_with-label-form_with+options) to solve this problem.

I've also added an autocomplete attribute to a different password field since the chrome inspector was complaining about that too.
