### ISSUE TITLE
Add profile field for fediverse username

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#1141]
We have a field for Twitter and GitHub usernames. With the current state of Twitter, it seems prudent to add support for Fediverse accounts.

I don't know if Mastodon/etc. does OAuth, but I would like to see some scheme for linking accounts to confirm they're real. Obviously we don't want any permissions to post on someone's behalf or read their timeline or anything, just confirm username.

**Comment by sknebel** [comment]
Mastodon (and I think some other fediverse software) does URL verification based on `rel=me` attributes. 

E.g. if you look at my profile at https://chaos.social/@HeNeArXn, it shows my website with a green checkmark because on my website I have a link `<a href="https://chaos.social/@HeNeArXn" rel="me">` , and Mastodon checks for this and recognizes a matching pair of such claims as confirmation they are indeed linked.

I see that lobsters already also uses `rel=me` on links to e.g. the users homepage, so this mechanism could apply here too - having a matching pair of fields would be green on Mastodon, and if lobsters were to check the reverse would also work. 

This would also be somewhat general and also useful for e.g. the website field in a profile, not specific to Mastodon - so maybe having the option to have multiple, general "this URL is also me" fields would be nicer than a Mastodon/Fediverse specific one?

**Comment by pushcx** [comment]
That sounds like a straightforward and scalable approach. I'm a little concerned that it would force people to link back to their Lobsters profile because I don't think they should be required to advertise their Lobsters profile on some other site to have us to link out. It just feels kind of manipulative, like we're trying to "growth hack".

And to scalability, so far all our integrations have been oauth-based so the amount of site-specific code is pretty minimal and has required darn-near zero maintenance, so it's worked out quite nicely.

**Comment by sknebel** [comment]
> EDIT: and Mastodon instances do indeed use a form of OAuth - given there are many instances they use some sort of dynamic registration, so instead of having to pre-register with the instance as you would register an app with Github or Twitter, this can be done dynamically with a POST request before the login flow.

Here are the relevant documentation bits about that: https://docs.joinmastodon.org/client/token/ for the registration and then https://docs.joinmastodon.org/client/authorized/ for using it/scopes etc

**Comment by icyphox** [comment]
OAuth and `rel="me"` links are largely Mastodon specific. I think the ideal solution to this would (and should) be implementation agnostic.

**Comment by winks** [comment]
> OAuth and rel="me" links are largely Mastodon specific. I think the ideal solution to this would (and should) be implementation agnostic.

rel=me is the standard approach and I don't see any reason why any other activitypub wouldn't possibly also do this, so I don't see how that would be a problem.

**Comment by skyfaller** [comment]
> I'm a little concerned that it would force people to link back to their Lobsters profile because I don't think they should be required to advertise their Lobsters profile on some other site to have us to link out.

It is theoretically possible with rel=me to link from the <head>, so the link isn't visible: https://front-end.social/@henry/109377568830957357

Of course, unless you're on a single-user instance you probably don't have that much control over your HTML, but I just wanted to mention it as an option.

Perhaps Fediverse apps should allow more than Mastodon's four public links, and somewhere in settings also verify other accounts in a more hidden fashion.

**Comment by pushcx** [comment]
Done in #1175
