### ISSUE TITLE
Comments associated with wrong subtree

### ISSUE THREAD

**Issue by natecraddock** [lobsters/lobsters#1195]
I've been following along with this thread today: https://lobste.rs/s/ehzhcw/semantic_markup_for_callouts. On multiple occasions I have noticed comments displayed in an incorrect subtree.

For example, [this thread](https://lobste.rs/s/ehzhcw/semantic_markup_for_callouts#c_ahewgg). I believe the reply from toastal should be below the comment from singpolyma. Also note that toastal somehow edited the reply 19 minutes before the comment from gpanders was created!

<img width="851" alt="SCR-20230829-jyln" src="https://github.com/lobsters/lobsters/assets/7967463/1cff784a-cdaf-4c02-a81e-c9bd8828e8da">

When I first saw this, I thought someone had just accidentally replied to the wrong thread. But I've refreshed the page several times, and the ordering of comments in the subtrees continues to change unexpectedly. Here's another example where the comments are nested under singpolyma's top level comment rather than gpanders (threads collapsed to keep the screenshot small):

<img width="795" alt="image" src="https://github.com/lobsters/lobsters/assets/7967463/0e319003-adf4-45d6-83f0-2bb51600eda5">

I've noticed this while logged in on Safari, and in Chrome logged out. Looking through recent commits there are some related to rendering comment threads, possibly related?

**Comment by pushcx** [comment]
Uh oh. Well, it's almost certainly related to #1190.

I output every thread tree to compare against the original threading code and got rounds-to-identical results (there's some minor ordering differences because the original doesn't specify how to break ties on duplicate scores). Maybe there's something wrong here with in-progress threads. I'm digging in.

**Comment by pushcx** [comment]
OK, I can repro the bug. Under not-yet-determined circumstances, there's an extra `</ol>` getting printed that's causing replies to appear to be to a higher-level ancestor than their direct parent.

...and luckily just a few minutes ago, @epilys and I were in [#lobsters](https://lobste.rs/chat) kicking around recursive CTEs, and worked out a way to get the `reply_count` field [I wanted](https://github.com/lobsters/lobsters/pull/1190#discussion_r1308708093) to avoid exactly this kind of awful bug in tracking depth for slinging html tags.

**Comment by pushcx** [comment]
It wasn’t an extra `<ol>`.

`confidence` has many duplicate values. The value for 1 upvote from author, zero flags on every brand new comment is very common! The 3rd byte on `confidence_order`, the tiebreaker based on `id`, is vital in new threads. Otherwise it’s a constant problem as new comments come in with identical `confidence_order` values. Not just a problem with top-level comments and sibling comments, it’s even a problem for (as was seen here) two depth 1 replies when the parents both have that same `confidence_order`.

I papered over this in prod the last few hours by intermittently running `update comments set confidence_order = concat(left(confidence_order, 2), char(id & 0xff using binary)) where id >= [id of a comment from just before deploy] and id & 0xff != 0 and hex(right(confidence_order, 1)) = "00"; `

The proper fix is in 510fd3c, to add an `after_create` callback that immediately fills `confidence_order` with the autogenerated `id` of the new record.

It’s possible this isn’t enough entropy and I’ll have to shift to two bytes for the `id` section of `confidence_order`. I’m going to write a query to see how often this error happens in prod (`confidence_order_path` duplicated between two comments on the same story with different `comment_parent_id`).

**Comment by msfjarvis** [comment]
Not sure if it's fully related, but the `indent_level` field in the JSON API (for e.g. https://lobste.rs/s/ehzhcw/semantic_markup_for_callouts.json) is now always `null` which seems to have happened in the last 10-12 hours. Is the change intentional? I was using it in [my app](https://github.com/msfjarvis/compose-lobsters/) to cheaply render comments without building up the full ancestor tree so it'd be helpful to know if I should be changing how I handle comments.

**Comment by pushcx** [comment]
It was related, yep. I’ve fixed it in fe09e5aa by replacing the `indent_level` field with `depth`, which is 0 for top-level comments and adds 1 for each level of reply.
