### ISSUE TITLE
Flag menu displayed in background when submission hidden

### ISSUE THREAD

**Issue by FrostKiwi** [lobsters/lobsters#1206]
Clicking `flag` after hiding a post displays the drop-down menu behind the comment box, making it unreadable.
This issue is the same as https://github.com/lobsters/lobsters/issues/601, but that was already closed with a pull request, so I created a dedicated issue for it.
![image](https://github.com/lobsters/lobsters/assets/60887273/d61b44f8-4073-4edf-9f96-1176be96c411)

**Comment by pushcx** [comment]
This is like the 4th time this bug has happened, so it would be great if whoever fixes it could improve the CSS so it stops happening. Maybe there's a better way to structure the CSS, maybe there's a test we could add, I don't know.

**Comment by JuanVqz** [comment]
Hey @pushcx I have a question on this.
Why are we hiding elements? is it because we are not interested in them? If so, I think the only option that should be visible when is hidden is unhide, once restored yeah you can interact with the item. what do you think?

Also, the hide status is not persistent... when reloading the browser it is shown again, is that expected?
