### ISSUE TITLE
web UI for hat doffing

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#1247]
Lobsters has [hats](https://lobste.rs/hats) so users can comment on behalf of projects. Unfortunately there's no web UI for doffing a hat so it's no longer usable.

For this ticket, add a "doff" link next to each hat on someone's profile (similar to the "disconnect" link for github/mastodon on /settings). The link should go to a form with one text entry to use as the "reason" message in `Hat#doff_by_user_with_reason`.
The link and form should only be visible/usable by that user and mods.

**Comment by kernal053** [comment]
Hi @pushcx. I'm working on this feature. Below I have added few screenshot for reference and suggestion.
 
I have added "Doff" link next to hat on user's profile
<img width="507" alt="Screenshot 2024-07-14 at 2 13 11 PM" src="https://github.com/user-attachments/assets/1ee0f408-772f-4aec-a3ae-d5578b2d37a0">

This link takes user to form for doffing a hat with "reason" message
<img width="865" alt="Screenshot 2024-07-14 at 2 13 53 PM" src="https://github.com/user-attachments/assets/e57f8852-ebc7-498f-8ee2-97dee49c18cf">

I have few questions:

1. What should be placeholder text in "reason" field ? Do I need to add/remove any field in the form ?
2. Do I need to write test cases for this feature ?

Since, it's my first open-source contribution here please guide along. Thanks

**Comment by pushcx** [comment]
I think the form + overall UI are great, you did well by reusing the site's existing styles. For the reason field, please make it a single-line `text_field` rather than a `text_area` to encourage short responses. It doesn't need a placeholder then, but follow it with a `.hint` span (examples in `app/views/settings/index.html.erb`) saying `Short public explanation, like "Left project"`

A feature spec would be great. This is the kind of infrequently-used feature that's easy to not notice we've broken. It could be as simple as creating a user with a hat, `sign_in user` to fake their login, load the profile page, click the "Doff" link, put something in the reason field, click the button, see that the reason is visible + modlog entry is made. We don't need to cover all the corner cases, one smoke test goes a long way with this kind of straightforward CRUD action.
