### ISSUE TITLE
Unable to log in on any browser/device

### ISSUE THREAD

**Issue by joshuacc** [lobsters/lobsters#1277]
I'm no longer able to log into lobsters at all on any browser or device. Fortunately, I still have an active session on my phone, but new logins are a no go.

Each time I attempt to log in I receive a 422 http error. The error response also doesn't have any HTML/JSON content that might provide guidance on fixing the issue.

My lobsters username is `joshuacc` in case that helps track down the issue.

**Comment by bbrks** [comment]
I've also had this issue for a while now (many weeks). Thought there was something weird about my browser until I just saw the response status and tracked down this issue.

**Comment by bbrks** [comment]
#1267 looks very similar

**Comment by bbrks** [comment]
Anything I can do to provide more information? It appears that the error is server-side and being swallowed/hidden behind HTTP 422. I have not been able to use lobsters for months due to this bug.

I have 2fa enabled, username bbrks. The error appears after submitting login form with password.

**Comment by pushcx** [comment]
It’s a validation failing that the password is too long. I’m investigating.

**Comment by pushcx** [comment]
Is it possible you have generated a password that’s longer than 72 bytes? I’m pretty sure you must but would like to confirm.

The login flow [updates password digests](https://github.com/lobsters/lobsters/blame/master/app/controllers/login_controller.rb#L64) to use the current number of rounds of bcrypt hashing, but if the password is very long there’s [a limitation in bcrypt](https://ruby.social/@garrettdimon/111098708322288267) that it only accepts 72 bytes. This doesn’t seem to be communicated clearly up the stack, I turned up a bunch of bugs ([sample](https://github.com/rails/rails/issues/47600)) and confusion at various layers. This is also awkward to handle because most all the higher layers think in terms of characters, which are potentially multiple bytes, and then the distinction has to be communicated to end users. (Lobsters is [unusually familiar](https://lobste.rs/s/pnysdr/lobsters_emoji_adoption) with Unicode and I still struggle to write an actionable error message.)

I didn’t research which recent update brought in this limitation or why - I’m curious but not _that_ curious.

I am really reluctant to chop passwords down to their first 72 bytes. This seems to be a pretty uncommon user behavior, so I’m going to add an error message instructing users to use the ‘forgot password’ flow to reset to a new password.

@bbrks @joshuacc Could you both confirm that you have long passwords, that your next attempt to login gets the error message, and that resetting to a <72 byte password works for you?

**Comment by pushcx** [comment]
Addressed in 9b4f6e1a9de8b48529a8ddcde6f68554314d5174 but I typo’d this issue number (#1127 vs #1277)

**Comment by joshuacc** [comment]
@pushcx Yes, I had a very long password. Using the reset password flow and replacing it with something shorter now allows me to log in on other devices again. 

Thanks for identifying the issue!

**Comment by bbrks** [comment]
I do have a long password! That would explain it. Thank you for looking into this

**Comment by pushcx** [comment]
Great, thanks for this. Sorry we had this bug, but I'm glad it's reasonably well-addressed now.
