### ISSUE TITLE
Broken confidence and confidence_score calculation for comments

### ISSUE THREAD

**Issue by dzwdz** [lobsters/lobsters#1318]
## the bug
[JaDogg's comment on the xz story](https://lobste.rs/s/uihyvs/backdoor_upstream_xz_liblzma_leading_ssh#c_kwgiuz) is above several "normal" comments despite having a score of -10 according to the [json api](https://lobste.rs/s/uihyvs.json) (edit: I just want to note that all deleted comments have a score of -10).

![image](https://github.com/user-attachments/assets/0243108a-af30-4ff9-b3b7-4fb1d1a19113)

## my investigation
I think I've already figured out the culprit:
https://github.com/lobsters/lobsters/blob/e199bbc362ccbb2ee9f5a46023117b594d6c8e2f/app/models/comment.rb#L184-L199

If we compare this to [Reddit's implementation](https://github.com/reddit-archive/reddit/blob/753b17407e9a9dca09558526805922de24133d53/r2/r2/lib/db/_sorts.pyx#L70-L85), `n` should be the total amount of votes (`upvotes + downvotes`), and `p` should be the upvote percentage (`upvotes / (upvotes + downvotes)`).

The `score` of old comments [seems to equal](https://github.com/lobsters/lobsters/blob/e199bbc362ccbb2ee9f5a46023117b594d6c8e2f/app/models/vote.rb#L126-L174) `upvotes - downvotes` (let's pretend flags are downvotes). So, when calculating the confidence of comments with a negative score, we substitute a negative `n`, which [gives us bogus results](https://gist.github.com/dzwdz/e2f151f84f14db5693c36b7dbc3e7665#file-confidence-rb). A score of -1 puts us between comments with scores of 1 and 2, for -2 we jump into 244% confidence, which slowly decreases until 106% confidence at -10.

If we were ordering comments just based on the confidence, then comments with `score <= -2` would then rise above all others. However, we convert the confidence to `confidence_order` first, and there's an overflow there. If I [run the query myself](https://gist.github.com/dzwdz/e2f151f84f14db5693c36b7dbc3e7665#file-mysql) for a score of -10, I get... a `confidence_order` of `FFFF`, the worst possible. I guess the `confidence_order` of this comment was calculated before https://github.com/lobsters/lobsters/commit/1414e96c3ce59bc96806684889997fe37fc0ef5a, and it's affected by something else.

The incorrect `confidence` is still a bug, though - even if we get the correct `confidence_order` for incorrect reasons later on.

## side note about ordering by score
Near the end of [today's stream](https://push.cx/stream/2024-09-05-you-re-allowed-to-be-evil-in-performance-code) @pushcx considered ordering the comments purely by their score instead (as that would allow better use of the three bytes of `confidence_order` dedicated per comment).

This is pretty much already the case (sans this weird behaviour for negative scores), since `score` is the only input for the confidence calculation. I think this means we could safely calculate the `confidence_order` based directly on the score without changing the comment order at all (although I maintain my position that it'd be worth it even if the order changes).

### clarification from pushcx + context
> 23:15 \<pushcx> To your last paragraph - when I was saying order based on score, I was trying to say drop the idea of calculating confidence. Just use score directly. I'm sorry that didn't come across; after a couple hours of running narrative I get kinda jumbled.
23:15 \<dzwdz> ah, fair
23:15 \<dzwdz> then yeah you were correct - it shouldn't change absolutely anything

For more context: Comments on a single level are ordered by `confidence_order` ascending. Right now the first two bytes are based on the confidence (see next comment about the details), and the last byte is the post id `& 0xFF` for [thread ordering reasons](https://github.com/lobsters/lobsters/pull/1190).

Since the lowest score is capped at -10, and the [highest scoring comment on lobste.rs so far](https://lobste.rs/s/slfdci/one_dozen_lobsters#c_nrfacp) is at 198, @pushcx suggested just using the first byte for the score (`(score+10).clamp(0,255)` to be exact) and using the last two bytes for the post id `& 0xFFFF`, which would make thread grouping less error-prone.

**Comment by dzwdz** [comment]
## how not to store the confidence
While I think the proper way to fix this is to just directly use the score, @pushcx told me to paste this in here:
```
-- this query is based on the query used to calculate confidence_order:
-- confidence_order = concat(lpad(char(65536 - floor(((confidence - -0.2) * 65535) / 1.2) using binary), 2, '0'), char(id & 0xff using binary))
MariaDB [(none)]> select hex(lpad(char(65536 - floor(((0.9 - -0.2) * 65535) / 1.2) using binary), 2, '0'));
+-----------------------------------------------------------------------------------+
| hex(lpad(char(65536 - floor(((0.9 - -0.2) * 65535) / 1.2) using binary), 2, '0')) |
+-----------------------------------------------------------------------------------+
| 1557                                                                              |
+-----------------------------------------------------------------------------------+
1 row in set (0.001 sec)

MariaDB [(none)]> select hex(lpad(char(65536 - floor(((0.995 - -0.2) * 65535) / 1.2) using binary), 2, '0'));
+-------------------------------------------------------------------------------------+
| hex(lpad(char(65536 - floor(((0.995 - -0.2) * 65535) / 1.2) using binary), 2, '0')) |
+-------------------------------------------------------------------------------------+
| 0113                                                                                |
+-------------------------------------------------------------------------------------+
1 row in set (0.001 sec)

MariaDB [(none)]> select hex(lpad(char(65536 - floor(((0.996 - -0.2) * 65535) / 1.2) using binary), 2, '0'));
+-------------------------------------------------------------------------------------+
| hex(lpad(char(65536 - floor(((0.996 - -0.2) * 65535) / 1.2) using binary), 2, '0')) |
+-------------------------------------------------------------------------------------+
| 30DC                                                                                |
+-------------------------------------------------------------------------------------+
1 row in set (0.001 sec)
```

`lpad` pads the binary string with `'0' = 0x30` instead of `'\0' = 0x00`.

If I fix the padding, then the results range from `0001` for 0% confidence up to `D556` for 100% confidence. We obviously aren't using the entire range of values. If I remove the `- -0.2` and `/1.2` parts, this happens:
```
MariaDB [(none)]> select hex(lpad(char(65536 - floor(0.0 * 65535) using binary), 2, '\0'));
+-------------------------------------------------------------------+
| hex(lpad(char(65536 - floor(0.0 * 65535) using binary), 2, '\0')) |
+-------------------------------------------------------------------+
| 0100                                                              |
+-------------------------------------------------------------------+
1 row in set (0.001 sec)

MariaDB [(none)]> select hex(lpad(char(65536 - floor(0.1 * 65535) using binary), 2, '\0'));
+-------------------------------------------------------------------+
| hex(lpad(char(65536 - floor(0.1 * 65535) using binary), 2, '\0')) |
+-------------------------------------------------------------------+
| E667                                                              |
+-------------------------------------------------------------------+
1 row in set (0.001 sec)

MariaDB [(none)]> select hex(lpad(char(65536 - floor(0.9 * 65535) using binary), 2, '\0'));
+-------------------------------------------------------------------+
| hex(lpad(char(65536 - floor(0.9 * 65535) using binary), 2, '\0')) |
+-------------------------------------------------------------------+
| 199B                                                              |
+-------------------------------------------------------------------+
1 row in set (0.001 sec)

MariaDB [(none)]> select hex(lpad(char(65536 - floor(1.0 * 65535) using binary), 2, '\0'));
+-------------------------------------------------------------------+
| hex(lpad(char(65536 - floor(1.0 * 65535) using binary), 2, '\0')) |
+-------------------------------------------------------------------+
| 0001                                                              |
+-------------------------------------------------------------------+
1 row in set (0.001 sec)

```
This is almost correct, except the value for a confidence of 0% makes no sense - I'd expect `FFFF`, not `0100`. This is because we the string we get is `010000`, which gets truncated by LPAD to `0100` (also, note how it keeps the beginning of the string rather than the end). I believe the correct query would be `select hex(lpad(char(65535 - floor(confidence * 65535) using binary), 2, '\0'));`, which makes use of the full range of values between `0000` and `FFFF`. It will still overflow for values outside of [0.0, 1.0], but I'm too lazy to fix that - we shouldn't be calculating confidence in the first place.

**Comment by pushcx** [comment]
I've been chatting with dzwdz on and off all day about his investigation. I want to call out that this kind of deep dive is a very valuable contribution to the site and thank him publicly. 

On top of the `lpad` bug that dzwdz diagnosed in his second comment, I want to be explicit that the change to `calculated_confidence` in 1414e96c that he notes in his first comment is also a bug. I misunderstood what `n` was getting initialized to and made a bad edit from `upvotes + flags` -> `upvotes - flags` (even setting aside the `* 2` that was my old attempt to increase the score influence of flags on comments and probably also incorrect).

One other thing we discussed today was the `- -0.2) * 65535) / 1.2)` scaling that appears in the sql. In prod the min `comments.confidence` is -0.1955 and max is 1.3806. (I recall seeing a max of 1.19, so this higher max is probably the result of bad edits to `calculated_confidence`.) I think I found in actual prod data we weren't using the full range of confidence values. I knew duplicate values were a problem but didn't fully appreciate that it was because so many comments only have a handful of votes. So that math was attempting to use the full 0-FFFF range of the first two bytes of `confidence_order`.

There's just so much going on here, so many layers of math and SQL hackery. I thought I'd tested it thoroughly but I'm embarrassed so many bugs have shaken loose. It's certainly fixable, but it's going to stay just as dangerous to edit.

Since the original implementation of `calculated_confidence` 12 years ago, the UI and cultural meaning of votes on the site has changed substantially. On Reddit downvotes are often used to express disagreement or dislike with many subreddits having light or nonexistent moderation; on Lobsters flags (still implemented as downvotes!) are rare and a signal to the more-involved mods. The confidence equation is valuable to Reddit because it differentiates a comment with score 1 because it has only the author's single upvote versus a comment with score 1 because it has 20 upvotes and 19 downvotes. That situation is not at all a regular occurrence on Lobsters! There is not a substantial difference to sorting comments by confidence or score (_probably_, this is worth double-checking). So that had me thinking that rather than fixing these 3 (so far!) bugs, maybe it would be better to entirely drop confidence and have the three bytes of `confidence_order` be one byte of `245 - score` (to account for `FLAGGABLE_MIN_SCORE`; and clamped to avoid underflow on the highest-voted comments) and two bytes of 

Finally a small note, I realize I didn't explain in #1190. The whole reason for `confidence_order_path` goes through all the contortions casting things into and out of a string because MariaDB doesn't provide an array type. At a fundamental level, though, a string is an array of bytes and the naive lexiographic `order by` works in byte order. However, if `confidence_order_path` gets too wide, eventually the cost of wide rows overwhelms the benefit of the optimization and sorting in the database slows substantially. I have not found any other example of writing a recursive CTE that does a tree sort like comments require. Maybe at least the RCTE queries could be substantially simplified if someone's aware of a better way to sort.

**Comment by dzwdz** [comment]
> One other thing we discussed today was the - -0.2) * 65535) / 1.2) scaling that appears in the sql. In prod the min comments.confidence is -0.1955 and max is 1.3806. (I recall seeing a max of 1.19, so this higher max is probably the result of bad edits to calculated_confidence.)

That sounds very wrong - isn't confidence a probability? Values outside of [0; 1] don't make sense at all. This probably means that `calculated_confidence` has been broken for ages.

I think [the last revision](https://github.com/lobsters/lobsters/blob/bd56afc30921e9562b620f5d19d1f18bd38bdd6c/app/models/comment.rb#L186-L199) was actually correct - if `score = upvotes - flags`, then we've had `n = score + flags*2 = upvotes + flags`, and `upvotes = score + flags = upvotes + flags - flags = upvotes`. Actually, looking at prior revisions, all of them seem correct? This makes me a bit confused about how you've ended up with out of range values...

> [...] Lobsters flags (still implemented as downvotes!) [...]

> There is not a substantial difference to sorting comments by confidence or score (probably, this is worth double-checking).

I don't think flags have been implemented as downvotes since https://github.com/lobsters/lobsters/commit/1414e96c3ce59bc96806684889997fe37fc0ef5a?
Still, since `score` is the *only* input to `calculated_confidence`, there are only two options:

1. calculated_confidence preserves ordering of scores - so ordering by score wouldn't change anything
2. calculated_confidence doesn't preserve ordering of scores - so there are pairs of scores `a.score, b.score` for which `a.score < b.score` but `a.confidence > b.confidence`, making comments with a lower score appear above comments with a higher score. This is very clearly a bug (remember that score is the only input!), and ordering by score would fix it.

**Comment by pushcx** [comment]
It's certainly possible `calculated_confidence` has been broken for ages. I have mostly treated it as an assumed-good black box and I don't think it's ever had any tests.

When I said flags are implemented as downvotes I was referring to the structure of the `votes` table, which records flags as a `Vote` with the `vote` column set to `-1`. Sorry, this topic keeps jumping up and down the levels of abstraction, it's hard to be clear.

For evaluating the difference between confidence and score, you're correct that `score` is currently the only input. Restoring the inputs back to upvotes and flags substantially improves the amount of information available for ranking via Wilson score interval. And getting back to [Evan Miller's post](https://www.evanmiller.org/how-not-to-sort-by-average-rating.html) I am knowingly suggesting implementing what he labels "wrong solution #1" because we see so few downvotes/flags that `score` and `confidence` are in practice very close to each other and `upvotes`.

**Comment by pushcx** [comment]
The migration took 190 minutes and 33 seconds to run in prod. Oof. But it's deployed!

Thanks again for doing such a thorough investigation of this code.
