### ISSUE TITLE
Prevent users from submitting stories that have an origin not previously seen

### ISSUE THREAD

**Issue by NattyNarwhal** [lobsters/lobsters#1352]
New users can't post previously unseen domains in a new story. It seems logical that this should extend to the new origin system, as often i.e. links to GitHub, dev.to, Medium, etc. URLs were used to evade the new domain ban.

**Comment by pushcx** [comment]
It's [present](https://github.com/lobsters/lobsters/blob/876ba880d3a66d7b0da288fa6f6b5b9c167cdcd4/app/models/story.rb#L179) but commented-out because I worried about the false-positive rate. The restriction on unseen domains has a false positive rate ~15%, where it prevents a topical, non-self-promo link.

I think I'd like to go a more-complicated direction and put stories from unseen domains/origins from new users into a queue for existing users to look at.

**Comment by NattyNarwhal** [comment]
A queue sounds good. IRC kinda functions as an informal queue in that new users can ask "hey, can someone submit my article" and someone posts it for them if it's any good. But that assumes a user would check on IRC first (unless the submit form guided them that way).

**Comment by pushcx** [comment]
Yeah, I think we've seen it work pretty well when people head there, but I have enough concerns about [IRC UI](https://push.cx/discord-vs-irc-notes) (especially the 5 bullets under "Desirable Features -> good new user experience") that I hesitate to send unfamiliar users to IRC.
