### ISSUE TITLE
lobste.rs is down

### ISSUE THREAD

**Issue by singhstronaut** [lobsters/lobsters#1391]
![image](https://github.com/user-attachments/assets/fc69bc26-0274-42d9-a532-286094b3f682)

**Comment by SansGuidon** [comment]
yeah, same here, what is weird is several down detector sites report it as UP.

**Comment by jmiven** [comment]
Are you using Brave? If so, it is expected: https://github.com/lobsters/lobsters/issues/761

**Comment by singhstronaut** [comment]
Ohh yes @jmiven .. Just verified on Edge and Firefox. Its working there.
Its not working only on Brave.

Issue Reference : #761 
Also : https://github.com/lobsters/lobsters-ansible/issues/45

**Comment by SansGuidon** [comment]
I was suspecting this sadly, yes I'm using Brave. May I ask ? Is it the end of the game then for Brave users?

**Comment by SansGuidon** [comment]
I'm likely not smart enough but I don't understand what we can do to solve the problem? So brave is banning lobste.rs ? Or the other way around? I checked the linked issue but I'm still confused.

Thanks for the help.

**Comment by pushcx** [comment]
Lobsters has tried to block Brave for years. Our code is open source and Brave read it to decide to spoof their User-Agent header to us to evade our block. I'm trying not to waste a lot of dev time on an arms race with them because a small forum with a couple volunteer contributors is unlikely to effectively compete with a [Peter Thiel-funded](https://www.vcnewsdaily.com/brave-software/venture-capital-funding/tcsztrbtby) cryptocurrency project that can afford full-time devs.

**Comment by SansGuidon** [comment]
Ok thanks for clarifying. I'm likely too naive user here. But so I guess it's the end of lobste.rs for now for many users as Brave has a growing fanbase.

**Comment by pushcx** [comment]
You're welcome, best wishes.
