### ISSUE TITLE
Feature: Send Webmentions

### ISSUE THREAD

**Issue by voxpelli** [lobsters/lobsters#383]
### Idea

In the lights of the very good discussions that take place on Lobsters and the problem with discovering that discussions if one isn't aware of it haven taken place on Lobsters I think it would be interesting if support could be added for sending the submission of the link as a [Webmention](https://webmention.net/) for any site that advertises that it accepts Webmentions.

That way the original site will know about the discussion going on here and people from elsewhere will be aware of the discussion. (Whether that is wanted or not is another thing, this feature suggestion assumes that more people finding the discussions would generally be a good ting)

### Implementation

As Lobsters already fetches and parses a page for the existence of eg. a rel-canonical, adding a check for a rel-webmention as well would be easy.

To then send a POST request with the Lobster page as "source" and the submitted page as a "target" should be easy (although maybe one wants to limit it to when it has received some kind of activity rather than just a plain submission).

### Icing on cake

An icing on the cake would be if any comment to that submission could then also trigger Webmention pings (as a simple variant of [Salmentions](https://indieweb.org/Salmentions), an advanced way to make webmentions travel upstream when used in a microblog/social scenario of indie-sites). That way the entire comment tree could be presented on the Webmention accepting page for those who accept and show full comment trees.

To make the icing on the cake work and to make the initial Webmention a bit clearer about what mention it actually is, it would be good to mark up the bookmark with [Microformats](https://indieweb.org/h-entry): http://indieweb.org/bookmark#How_to_markup And the comments as: http://indieweb.org/comments#How_to_markup

That's not necessary for Webmentions in itself, but the [IndieWeb](http://indieweb.org/) community that has spearheaded Webmentions suggests that one does it, to convey as much useful information as possible. Sending a Webmention without Microformat data is better than sending none though, one can then use other metadata to present it in a nice way.

**Comment by crertel** [comment]
I'm not sure that having folks meandering over to Lobsters because somebody linked their blog is a great idea--especially if it's just to fuel the outrage machine. Additionally, I'm not sure how I feel about having yet another way of opening up our data to advertisers and spammers and the like.

Webmentions seems to mostly serve that purpose.

**Comment by voxpelli** [comment]
Yeah, I agree that it's not necessarily a wanted thing.

> Additionally, I'm not sure how I feel about having yet another way of opening up our data to advertisers and spammers and the like.
> 
> Webmentions seems to mostly serve that purpose.

This interpretation sounds needlessly hostile. The adoption of Webmentions as well as it's standardization within the W3C has been driven by the wish to decentralize social media and been pushed by the IndieWeb community in particular as the way to notify actors about social interactions that are relevant to them – just as Twitter, Facebook etc use notifications to notify actors on their platforms about social interactions that are relevant there.

Of course all mechanisms can be abused and it's mentioned among the [security considerations](https://www.w3.org/TR/webmention/#preventing-abuse) of Webemtnions  and there are initiatives like [Vouch](http://indieweb.org/Vouch) to further address it.

But in no way has this been made to serve advertisers or spammers, it's been dogfooded by people who wants to see social media less centralized and more independent and created to serve _mostly that purpose_.

Is the concern of yours that advertisers and spammers would start submitting pages to Lobsters just to get a Webmention sent to that site? Not sure what value that would add for the advertiser/spammer.

**Comment by cweiske** [comment]
As a blog owner, I like to get notified that my posts are linked/discussed somewhere. Without sending 
 webmentions/linkbacks, I only find out because people tell me or because I look in the referrer list of my logs.

**Comment by jcs** [comment]
I'm not opposed to it, feel free to send a PR for it.

**Comment by NinjaTrappeur** [comment]
I'm up to implement this if it has chance to get merged.

My plan is to implement webmentions in the lobsters => aggregated website direction, ie. no incoming data towards lobsters, ie. no incoming spam.

I would like to send a notification when:

- A story linking my website is sumitted.
- A new comment to the previous story is submitted? (not sure about this one)

So it would look pretty much like this:

1. User submit the story.
2. fetched_attributes parse the webpage, find the webmention endpoint (if any) and save it in the Story model.
3. The story is inserted in the database, [a webmention](https://www.w3.org/TR/webmention/#sender-notifies-receiver) pointing the new story is sent to the previously parsed endpoint.
4. ???? For each new comment a webmention pointing the new comment is sent ?????

We would need to:

- Add some [micro-formats](http://microformats.org/) classes to the story template.
- Add a new field storing the website webmention endpoint to the Store Model.
- Parse the webmention endpoint in the [fetched_attributes](https://github.com/lobsters/lobsters/blob/master/app/models/story.rb#L861) function.

Do we want this?

**Comment by pushcx** [comment]
Thanks for stepping up! This would be great for stories, but feels like it'd be spammy for comments. Especially when they go to a system that displays webmentions (like I think Wordpress supports/defaults to), a busy story could overwhelm someone's page in a way that looks like we're trying to promote Lobsters at the expense of their site.

Your steps look good. Step three, sending the mention, shouldn't be called directly from the controller so that story creation doesn't hang for seconds if their webmention endpoint is slow. The mailing list mode has an example of this in `script/mail_new_activity`, which is run every 5 minutes by a cron job in the lobsters-ansible repo. Unless someone has a better suggestion, let's go with this same approach of having a cron job fire a script every few minutes, with the script keeping track of where it left off in `Keystore`.

Open question: do we want to send webmentions going back through all our stories, just the last few weeks/months, only for the future? (I can manually enable the job with set the appropriate `Keystore` value to whatever's appropriate before deploying this to give a first run hours/days to run if needed.) I lean towards the sending mentions for all stories but haven't thought through consequences.

**Comment by NinjaTrappeur** [comment]
Thanks for your feedback and indications! 

According to the #indieweb-dev irc folks, we can start by just sending only the new webmentions.

I guess if we change our mind at some point, we would still be able to send the historical data if we keep the last sent webmention timestamp somewhere in the Story model .

**Comment by pushcx** [comment]
Done in #535
