### ISSUE TITLE
Skylight Instrumentation

### ISSUE THREAD

**Issue by chancancode** [lobsters/lobsters#454]
Hello!

I work at [Skylight](https://www.skylight.io/). We are launching a [program](https://www.skylight.io/oss) to offer free Skylight accounts to open source apps (similar to Github and Travis), so I am reaching out to see if this is something you would be interested in.

If you’re not already familiar with Skylight, it is a smart profiler for Rails apps. Skylight makes it easy to pinpoint performance issues in Rails applications.

We work on a lot of open source projects ourselves, and in our experience it can be pretty hard to get contributors to work on application performance issues. Few contributors consider working on performance problems, and the ones that might be interested may not even know where to start. By making performance information more accessible, we hope to inspire potential contributors to tackle slow parts of your app, and have a good way to see if their contributions helped.

For reference, this is the [Skylight dashboard](https://oss.skylight.io/app/applications/g0gJSNnzYAws/) we set up for [The Odin Project](https://www.theodinproject.com/). It should give you a pretty good idea of how Skylight works.

Integrating Skylight to a Rails application is very easy. All you have to do is add the gem to your Gemfile and set an environment variable with your authentication token. (We are happy to send a pull request.) If you’re interested in setting this up or if you have any questions, you can reach us here or at [support@skylight.io](mailto:support@skylight.io).

We'd also love to feature you on our [website](https://www.skylight.io/oss) as one of the first open source organizations using Skylight. We hope you’ll join us in helping to make performance an accessible way to contribute to an open source project!

**Comment by pushcx** [comment]
@chancancode I think that'd be great to try now that we've stabilized our hosting and deployment, if you'd like to create a PR. Every couple weeks I see a rash of failed queries starved of database connections, I'd love to start gathering metrics to run that down.

**Comment by pushcx** [comment]
(moved comment here from PR #475 and reopened so I don't forget about this)

@chancancode Doesn't look like data's arriving. I saw the note about exiting and fresh-staring a new unicorn process and that doesn't seem to have helped. (And yes, the app is running in production environment on a supported Ruby version and Linux server.)

Please set me as the owner for the Skylight project.

The "open source" link on [the app page](https://www.skylight.io/app/applications/UVOwCQJiWlFy/recent/5m/endpoints) is broken in an interesting way: it opens a new tab to the same page where I have a "Sign Up for Skylight" button instead of an indication that I'm logged in.

**Comment by pushcx** [comment]
My cron jobs are barfing email at me every few minutes:

```
W, [2018-04-11T14:10:04.089921 #7439]  WARN -- : [SKYLIGHT] [1.6.0] Unable to start Instrumenter; msg=authentication token required; class=Skylight::ConfigError
W, [2018-04-11T14:10:07.943642 #7451]  WARN -- : [SKYLIGHT] [1.6.0] Unable to start Instrumenter; msg=authentication token required; class=Skylight::ConfigError
W, [2018-04-11T14:10:12.215449 #7543]  WARN -- : [SKYLIGHT] [1.6.0] Unable to start Instrumenter; msg=authentication token required; class=Skylight::ConfigError
```
even though I've added `ENV['SKYLIGHT_AUTHENTICATION'] = 'token I was emailed'` to `config/initalizers/production.rb`. This is :frowning_face: I'd appreciate any help before my inbox is overwhelmed.

**Comment by pushcx** [comment]
Looks like data is flowing and my inbox is quiet.

**Comment by pushcx** [comment]
I've spent some time poking around. This doesn't seem to be actionable. It's warning that `StoriesController#show` can be slow and I care because I recognize it as the most popular page on the site. It calls out a warning that sounds like it's a classic 1 + n query:

![screenshot-2018-4-11 skylight](https://user-images.githubusercontent.com/6262/38633003-f4cc8ba8-3d83-11e8-91b2-bc84f17a8cdc.png)

And... Ruby is not exactly great for static analysis of call graphs. What code made this call? How many times? `Keystore` is never explicitly referenced in `StoriesController`, so I guess I can pull up the code and try to read down every included file and every call and every model callback and try to find every time they mention `Keystore` or call some code that does? And the line above for `StoriesController#show` has a big chunk of the runtime that I guess comes after the `Keystore` access but before the rendering. Your [performance docs](https://www.skylight.io/support/performance-tips) start from "looking at a graph", skip over identifying the source of problems, and then talk about optimization tweaks. Am I misunderstanding, or missing something because I'm not seeing the admin view?

**Comment by pushcx** [comment]
Any suggestions or timeline for docs? I'm a little puzzled as to what could be improved, I've tried clicking everything in the app in the hopes of details (yay, material design) and not seen any more info available.

**Comment by wagenet** [comment]
@pushcx have you read the main Skylight guides: https://www.skylight.io/support/skylight-guides ?

**Comment by wagenet** [comment]
As for actionable, a good example is https://oss.skylight.io/app/applications/UVOwCQJiWlFy/recent/6h/endpoints/HomeController%23tagged?responseType=html. It's one of the more agonizing requests (as seen in the endpoint view) and it's clear that the SQL query is what's taking up the bulk of the time. If you want to make that request faster, the best place to start is the SQL query, either by optimizing it or adding caching around it.

**Comment by wagenet** [comment]
@pushcx first off, I wouldn't spend much time worrying about the "SELECT from keystore" query as it only takes up about 2% of the overall request time (evident by the small bar). It may be an N+1, but it's not doing any significant harm. That said, a quick scan of your code leads me to believe that it's coming from here: https://github.com/lobsters/lobsters/blob/2105656d8f3c805a61a289da84b3ad5ab4abe883/app/controllers/application_controller.rb#L37. This is a `before_action` on every controller action, so it would apply here as well. FWIW, I think we could probably show these separately on the event sequence.

**Comment by pushcx** [comment]
Thanks for looking at this and confirming that only way to work on a problem Skylight identifies is to have total knowledge of every line of code that might trigger a query or render a view along with the production inputs, none of which are available from Skylight.
