### ISSUE TITLE
Use Dependabot to keep dependencies up-to-date

### ISSUE THREAD

**Issue by greysteil** [lobsters/lobsters#467]
A few dependencies are a little out-of date. Would you be up for using [Dependabot](https://dependabot.com) to automatically keep them up-to-date?

**Comment by greysteil** [comment]
I'm happy to help review and fix-up the initial batch of updates - getting up-to-date is normally the hard bit.

**Comment by pushcx** [comment]
I've signed up for this and put it on a monthly schedule.

**Comment by pushcx** [comment]
It opens a PR for each dep instead of one, and this is not configurable. Uninstalling so I don't get (its max of) 5 PRs per month because, like every Rails project, there are dozens of deps.

**Comment by greysteil** [comment]
Fair enough! There’s a service called deppbot that will give you one PR with all updates bundled together.

**Comment by greysteil** [comment]
(Or you could just set it to automerge patch/minor releases, if that would work.)

**Comment by pushcx** [comment]
I am not thrilled about giving some random project write access to the repo; giving it that + a mandate to land commits on master is a non-starter. Mostly it's way noisier and busier than this small, slow project calls for; but also it'll probably introduce more instability than it fixes due to our thin test suite. I already had to commit 55da55cb9e9310c7fb2d814197a5824b2b02d5e4 to fix it introducing incompatible versions of AR + mysql2.

And as I'm digging in - I'd thought from the logo logo + name that this was a project from thoughtbot, but I see that's not the case. The homepage has zero information about who's behind this project and why I should trust them with write access to a repo. I mention this because I see from [the issue about this](https://github.com/dependabot/feedback/issues/11) that you're involved with it.

**Comment by greysteil** [comment]
Fair enough. Yes, it’s me behind it - sorry if that wasn’t clear. Thoughtbot are a customer, though!

Sorry to have wasted your time.

**Comment by pushcx** [comment]
It's not a waste of time because it's not a good fit for us, we still got all the dependencies bumped, so thanks for that. :smile:

**Comment by greysteil** [comment]
@pushcx - I just added a new option to Dependabot that I think will make it worth enabling on this repo again. You can now ask it to only create PRs for you for dependencies with a security vulnerability.

There's a blog post about it [here](https://dependabot.com/blog/security-updates-only) and I ran it against this repo and got [this PR](https://github.com/greysteil/lobsters/pull/1).

Shouldn't create any noise for you at all - just PRs that fix security vulnerabilities, which I'm guessing you want!

**Comment by greysteil** [comment]
@pushcx - FYI, there's another Nokogiri security vulnerability just been announced, which is patched in 1.8.5. If you switch on Dependabot in security-updates-only mode (under advanced options when you add a repo) then it'll create the update PR for you, and will make sure you have one in your inbox if/when there are any more vulnerabilities. 😎
