### ISSUE TITLE
Fix config/routes.rb specifying `scope :format => "html"`

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#482]
A user asked for a list of stories they've upvoted, preferably in json. I pointed out the `/upvoted` endpoint, but `/upvoted.json` was throwing 404s.

I worked around this in 9eae3e3c9daed5b52aaa60f5835c91542a951037 but it looks like this has been the case since 981759c34ff6eeb629b0cb54b029b1fc0001a611 in Jan 2014. I'm puzzled by this commit, because Rails doesn't try to do anything to support other formats unless there's a `(.format)` in the Route and code in the controller. I think this `scope` can be simply removed, but I don't have the attention to read more history for clues and test a fix now so I'm writing up a quick issue.

**Comment by pushcx** [comment]
Removed in d24e123 after discussion in #490.

**Comment by pushcx** [comment]
I realized a minute later it was silly not to clean up the redundant format requirements while it was fresh in my mind, so I did that in a59cf79.

**Comment by NinjaTrappeur** [comment]
Hey, I was checking out this PR, it actually introduce a "weird" behaviour: in case the controller cannot render the requested format, instead of returning a 404 (previous behavior), it will now return an empty template.

I don't think this is a big deal, just wanted to warn you. See https://lobste.rs/upvoted/page/1.wut .

We could prevent that by keeping the scope and changing its value with the array [html, json,rss]. Again, I'm not a rails dev, this could be wrong.

**Comment by pushcx** [comment]
I get an HTTP 406, so at least the header's right. I'm not sure under what other conditions Rails might throw 406 so I hesitate to share that template between the two. I'll leave it for now.
