### ISSUE TITLE
unused data

### ISSUE THREAD

**Issue by hyperloop-rails** [lobsters/lobsters#517]
https://github.com/lobsters/lobsters/blob/8db5de92652365bcd2763eaf2b7bf76e727c2d08/app/models/vote.rb#L70-L75

There is unused data retrieval, only comment_id, vote, reason of Vote is used, so the code can be modified to:
` votes = self.where(
        :user_id    => user_id,
        :comment_id => comment_ids,
      ).select(:comment_id, vote, reason)`

**Comment by pushcx** [comment]
This is not the correct refactoring of this code. Zoom out more.

**Comment by hyperloop-rails** [comment]
diff --git a/app/models/vote.rb b/app/models/vote.rb
index 4e78e74..e96ac38 100644
--- a/app/models/vote.rb
+++ b/app/models/vote.rb
@@ -72,7 +72,7 @@ class Vote < ActiveRecord::Base
       votes = self.where(
         :user_id    => user_id,
         :comment_id => comment_ids,
-      )
+      ).select(:comment_id, :vote, :reason)
       votes.inject({}) do |memo, v|
         memo[v.comment_id] = { :vote => v.vote, :reason => v.reason }
         memo

**Comment by pushcx** [comment]
This is still not the correct refactoring of the code.

Your paper turned up on Lobsters, that was useful context for this and #518: https://lobste.rs/s/u7srss/how_not_structure_your_database_backed#c_syfieu

**Comment by pushcx** [comment]
The patch isn't wrong. The patch looks like a bot outputting rules-based fixes rather than a human reading the code, because there's a better solution to this if you look at this function, and another better one if you look at the larger context in the app.

So if you have a bot, great, let's talk about your bot on the site and decide what would be useful. But running the bot and dropping micro-optimizations means you're volunteering me to be the human to spend time thinking about them.

I'm really happy to see the codebase was useful in your studies, because the time contributors spent on it is providing bonus value at no extra work. When you paste bot output and use that as a metric in your next paper as evidence of your bot's value, you're asking contributors to do new work for you. When it's micro-optimizations with no human judgement or even performance metrics, you're providing an extremely marginal benefit to the codebase that is not outweighed by the volunteer time required to do review it.

The problem is not that I don't understand what your patch does or what benefits you claim or what the general class of performance issue is. The problem is that you're not acting like you care about the costs.

**Comment by hyperloop-rails** [comment]
I feel so sorry to make you feel bad, and I appreciate a lot for your effort in responding to the issues I posted. 

Indeed we have a recently published tool (a RubyMine plugin) to help you identify such optimization and do automatic fix, as you can find here: https://hyperloop-rails.github.io/powerstation/, which you can try it on your own Rails project.

I'm not intended to make you feel that I'm using you--I apologize sincerely to hurt feelings--but want to improve the performance problem solving in ORM applications. Helping find out both performance-improving and semantics doable patches is one of our target. And your feedback about the costs concern really helps us a lot in our future work of better tools. 

Anyway, I apologize again for my mis-behavior.

**Comment by pushcx** [comment]
You didn't hurt my feelings, you repeatedly neglected to identify yourself as researchers so that professional work me and other maintainers into participating in and evaluating your research project without consent. My feelings aren't hurt by these code patches. For the final time, the problem is your misconduct as an academic researcher.
