### ISSUE TITLE
Accessing lobsters after install

### ISSUE THREAD

**Issue by Andrewskiz** [lobsters/lobsters#549]
Hey, this may be a ruby /web server question, I apologize if so as this is my first time using the framework and hopefully someone can point me in the right direction.

I have a CentOS 7 server running multiple sites, and just installed lobsters under a user with a vhost. When I try to run rails server I get this error:
/var/www/vhosts/myusername/.rbenv/versions/2.3.3/lib/ruby/2.3.0/socket.rb:205:in `bind': Address already in use - bind(2) for 127.0.0.1:3000 (Errno::EADDRINUSE)

I tried with a different port, but I can't access the server using the ip address and port. If I try to access the domain name, it just loads the apache page.

Thanks for your time.

**Comment by pushcx** [comment]
Yeah, this is a general rails hosting thing, but I can give a few pointers.

That error implies you already have a server running in another terminal or something. Run `netstat -pnlt | grep :3000` and the rightmost column should tell you the pid of the process, which you can stop or leave running.

You probably need to do some Apache config to tell it to proxy to the app server on port 3000. I don't know what this config looks like, we use nginx in production. The [ansible](https://github.com/lobsters/ansible) repo here has our full config, if it helps.

The Lobste.rs [chat room](https://lobste.rs/chat) is probably the best place for these kind of questions because people can ask for more details. There's usually a couple people familiar with running the codebase during US daytimes.

Good luck, and please email me when you get your site running so I can add it to our list of sister sites. :)
