### ISSUE TITLE
Navbar style on "Newest" page has a weird linebreak

### ISSUE THREAD

**Issue by antifuchs** [lobsters/lobsters#580]
On a normally-wide Chrome window, the "Newest" page's nav bar has an odd line break in it:

![screen shot 2018-10-20 at 10 42 11](https://user-images.githubusercontent.com/11864/47253554-d8890580-d454-11e8-9cf1-0e4bbebab9b7.png)

I'm assuming this is because the character widths of the elements on that bar add up to being too wide, but it's still pretty weird. Maybe, as a work-around, "Newest Stories" could be abbreviated, or promoted to the bar somehow?

**Comment by pushcx** [comment]
There are a number of pages that exhibit this behavior, like [user threads](https://lobste.rs/threads/pushcx), and [this commit](https://github.com/lobsters/lobsters/commit/4dec19d) fixed a really ugly problem with descriptions being long enough to not just have a funny break but wrap onto two lines.

So I've been increasingly wanting to redo this header because of these layout issues, but I know changing prominent design elements like the nav is upsetting, so I'd like to do it once rather than incrementally.

I'd like a clear split so the left items are all "user-agnostic site navigation" and the right "personal navigation", meaning "Your Threads" needs to move to the right and possibly even just get dropped in favor of the the new Replies interface. Probably fold Messages into the Replies display so it's not a separate top-level element. When there's replies like "3 Replies", only the number "3" should be red rather than the whole thing, because it's a bit glaring now. We can probably drop the 'Home' that appears on any page that's not the homepage; clicking a site logo to return to the homepage is a well-established pattern on the web. I think we can probably drop the [karma display](https://lobste.rs/s/ddp01i/what_is_number_next_my_username_on_lobste) but I know that some users will be dismayed to lose that immediate feedback.

We have a few places we sort of have a subnav going on, like Home/Recent/Newest, Unread/All/Comments/Stories, Messages, and maybe want joining Saved/Hidden/Upvoted (I'm pretty sure /hidden and /upvoted are not linked anywhere).

And then, as you point out, we have titles like "Newest Stories" and the site is inconsistent about the use of on-page titles. [Submit Story](https://lobste.rs/stories/new) has a title under the nav, [Newest Stories](https://lobste.rs/newest) has it in the nav while [Recent Stories](https://lobste.rs/recent) has neither. There isn't a rule that "if you're on the page linked from the header, there's no in-page title, we just bold that link" because [Search](https://lobste.rs/search) is both bolded and has a title under the nav. Replies/Messages consistently have a title under the nav so you know which sub-page you're on.

On the flip site, the bottom nav is a grab bag of less-popular, non-personalized links. Probably [tags](https://lobste.rs/tags/) and/or [Top](https://lobste.rs/top) (which needs an hint for how to set the time period) should be linked here.

Finally, it would be nice if we had a little elbow room for future expansion.

So there's my braindump about navigation. I'm glad to get my thoughts in one places - does anyone have their own thoughts on navigation and its styling to add?

**Comment by evexoio** [comment]
@pushcx I'm willing to take on this,

I think what you said makes total sense. I was thinking about copying the good parts of HN's nav that we can apply here, like hiding "Your Threads" in the profile page for example.

If you can lay out the specs for the new nav, I'll work on it right away 👍

**Comment by pushcx** [comment]
milesrout noticed a minute ago in chat that /top isn't linked anywhere

**Comment by pjanx** [comment]
I have a simple request to put the score "(%d)" in a span element (navigated here by @pushcx).

**Comment by pushcx** [comment]
@pjanx This is live now. If you're looking to adblock your karma score from the header, the rule is `lobste.rs###headerright .karma`. (This may break when the header is redesigned, but if karma stays I'll make sure it's easy to block.)

As long as I'm writing - probably we should move the page layout to flexbox, we have a significant amount of jank with `#inside` and `.box` that is addressed mostly by not touching anything and backing away slowly.

**Comment by pushcx** [comment]
I've been tinkering with CSS and layout the last week or two as a way of warming up to this. If you have an opinion, now is an excellent time to discuss how to paint this bikeshed, or volunteer to do so.

If you are reading this after the PR has been merged and deployed and you have strong opinions on it: Hello, future painters. I hope these changes will prove to be a good improvement to site usability without being too disconcerting, and I look forward to your contributions. This issue has invited discussion or implementation for more than two and a half years. If you're going to make a case for a change now, you can make the best case for it based on site usage, which is available from [database queries](https://lobste.rs/about#queries), and I have [goaccess](https://goaccess.io/) available for web usage. Quickest turnaround is available in [the chatroom](https://lobste.rs/chat).

**Comment by pushcx** [comment]
I surveyed all the site routes for heading, legend, and subnav. I'm using the names for the variables and css classes because matching existing usage is clearer, though I don't think we need to stick with these names after redesign.

Here's a screenshot with the parts labeled in orange (and, yes, the linebreak that prompted this issue):
![nav](https://user-images.githubusercontent.com/6262/153089563-1bd8d311-d736-4b0d-a990-b03a5f8fe0e8.png)

The `Heading` is a link to the current page. It's ignored if links to one of the existing links on the left side of the header (Home Recent Comments Your Threads Submit Story Saved Search).

The `Legend` is a heading that appears below the nav with slightly larger bold text. Only the view of a private message has a sublegend.

`Subnav` appears to the right of the legend, under the right-side global nav.

Help text appears above the main content of the page ([/tags](https://lobste.rs/tags)) for most pages, but below ([/replies](https://lobste.rs/replies)) on a few pages that are exclusively seen by regular users who'll be very familiar with the page's function.


| Path | Action | Legend | Heading | Subnav |
| :--  | :--    | :-- | :-- | :-- |
| /                             | home#index |
| /404                          | home#four_oh_four | 404/User not found |
| /about                        | home#about |
| /avatars/:username_size.png   | avatars#show |
| /categories/:category         | home#category |
| /categories/:id               | categories#show |
| /chat                         | home#chat | Lobsters Chat |
| /comments                     | comments#index | | Newest Comments |
| /comments/:id                 | comments#show |
| /comments/:id/edit            | comments#edit |
| /comments/:id/reply           | comments#reply |
| /domain/:name                 | home#for_domain  | | #{domain} |
| /filters                      | filters#index | Filtered Tags |
| /hats/build_request           | hats#build_request | Request a Hat |
| /hats                         | hats#index | Hats | | Request Hat |
| /hats/requests                | hats#requests_index | Requested Hats |
| /hidden                       | home#hidden | | Hidden Stories |
| /hottest                      | home#index |
| /invitations/confirm/:code    | invitations#confirm_email |
| /invitations/:invitation_code | signup#invited | | Create an Account |
| /invitations                  | invitations#index | Requested Invitations |
| /invitations/request          | invitations#build | Request an Invitation |
| /login/2fa                    | login#twofa |
| /login/forgot_password        | login#forgot_password | Reset Password |
| /login                        | login#index | Login |
| /login/set_new_password       | login#set_new_password | Set New Password |
| /messages/:id/edit            | messages#edit |
| /messages/:id                 | messages#show | #{subject} Sublegend: Sent from #{author} #{hat} #{time} | | Back to [Sent] Messages |
| /messages                     | messages#index | Private Messages | | View Received/View Sent |
| /messages/new                 | messages#new |
| /messages/sent                | messages#sent |
| /moderations                  | moderations#index | Moderation Log |
| /moderators                   | users#tree |
| /mod                          | mod#index | Dashboard | | Notes Stories Comments |
| /newest                       | home#newest | | Newest Stories |
| /newest/:user                 | home#newest_by_user | | Newest Stories by #{username} |
| /privacy                      | home#privacy | Privacy Policy |
| /recent                       | home#recent | | Recent Stories |
| /replies                      | replies#all | All Your Replies | All Your Replies | Unread All Comments Stories |
| /replies/comments             | replies#comments | Your Comment Replies | Your Comment Replies | Unread All Comments Stories |
| /replies/stories              | replies#stories | Your Story Replies | Your Story Replies | Unread All Comments Stories |
| /replies/unread               | replies#unread | Your Unread Replies | Your Unread Replies | Unread All Comments Stories |
| /saved                        | home#saved | | Saved Stories |
| /search/:q                    | search#index |
| /search                       | search#index | Search |
| /settings/2fa_enroll          | settings#twofa_enroll | Login - Two Factor Authentication | #{title} | Back to Settings |
| /settings/2fa                 | settings#twofa | Login - Two Factor Authentication | | Back to Settings |
| /settings/2fa_verify          | settings#twofa_verify | | #{title} | Back to Settings |
| /settings                     | settings#index | Account Settings (View Profile) | | Logout |
| Note: /settings is divided by internal headings reusing the legend CSS class |
| /s/:id(/:title)               | stories#show |
| /signup/invite                | signup#invite | Pass Along an Invitation |
| /signup                       | signup#index | Create an Account |
| /stats                        | stats#index |
| /stories/:id/edit             | stories#edit | Edit Story |
| /stories/:id                  | stories#show |
| /stories/new                  | stories#new | Submit a Story |
| /stories/:story_id/suggest    | stories#suggest | Suggest Story Changes |
| /tags/new                     | tags#new | Tag Create |
| /tags/:tag_name/edit          | tags#edit | Tag Edit |
| /tags                         | tags#index | Tags |
| /threads                      | comments#threads | | Your Threads |
| /threads/:user                | comments#threads | | Threads for #{username} |
| /top                          | home#top | | Top Stories of the Past #{time} |
| /t/:tag                       | home#tagged | | #{tag} |
| /upvoted/comments             | comments#upvoted | Upvoted | Upvoted Comments | Stories Comments |
| /upvoted/stories              | home#upvoted | Upvoted | Upvoted Stories | Stories Comments |
| /u/:username/standing         | users#standing |
| /u/:username                  | users#show | #{username} (Send a Message) |
| /u                            | users#tree |

I guess the obvious thing here is that we are not at all consistent in how we use these parts of the site header! Heading and Legend fill the same role but we alternate, duplicate, and ignore them. Subnav does a couple jobs: it's a 'back' button (messages, settings), a couple related pages (replies), or a single action (hat, logout).

Right now I'm thinking the fix is to drop Heading entirely for Legend. This fixes the primary bug and makes the nav static, which is great for usability.

Subnav is kind of a junk drawer and I'm reluctantly OK with that. It would be visually nice to highlight the current top-level nav item and then line up subnav under that, but one of the places we use subnav is `upvoted` and it's not in the top-level nav. Which... I guess it should be? `/hidden`, `/saved`, `/upvoted/stories`, and `/upvoted/comments` are all related two ways: first, they're all site content the user has interacted with, and second: they're really hard to find. `/` (home page/"hottest"), `/recent`, `/newest`, `/top` could probably also share a subnav.

So top-level site nav (left) should be : Logo (linking home), Comments, Submit (if logged in), Search.

Your Threads has been in the header since launch but that functionality is much nicer in Replies. Let's see if users have adopted it:
`cat production.log | grep -v nobody$ | grep 'Request .* /replies' | awk '{print $NF}' | sort | uniq -c > /tmp/visited_replies` has X users who have visited a `/replies` page
`cat production.log | grep -v nobody$ | grep 'Request .* /threads/\([a-zA-Z0-9_\-]*\) .* \1$' | awk '{print $NF}' | sort | uniq -c > /tmp/visited_threads_count`
and then I hacked them together (because I couldn't figure out how to use Consolidation in Calc):

```ruby
replies = File.readlines('/tmp/visited_replies_count').map {|l| l.strip.split }
threads = File.readlines('/tmp/visited_threads_count').map {|l| l.strip.split }
combined = {}
replies.each {|r| combined[r[1]] = { replies: r[0] } }
threads.each {|t| combined[t[1]] ||= {}; combined[t[1]][:threads] = t[0] }
File.write '/tmp/visited_counts', combined.map() {|u, counts| "#{u},#{counts[:threads]},#{counts[:replies]}" }.join("\n")
```

Nope! Your Threads is way more popular than Replies. More users (732 vs 144), more total views (2744 vs 756), and even of the users who have used Replies, half use Threads more (71 of 144). I'm surprised, this is the reverse of what I expected. I'm going to PM a bunch of these users who prefer Threads to ask what I'm missing.

The top-level user nav (right) should be user-specific: Login and Filter for logged-out visitors or Filter, Messages, Replies (maybe combine Messages and Replies to an Inbox?), Settings, maybe "Saved" for the Saved/Upvoted/Hidden section. I'm still considering whether to drop karma: sometimes it's good at nudging users to follow site norms, sometimes it's confusingly reductive (most frustrating to me is having to chide new users about inappropriate comments and hearing that surely outright abuse is acceptable because they're net positive). Several users asked for karma to get a css class so they could remove it with ublock origin. Maybe karma would be worth the space if it linked to a page with a big table of events that moved the user's karma up or down, like "+6 for this comment" or "-8 for this [deleted story](https://github.com/lobsters/lobsters/commit/5f5fa8ef0307530273da9a1c6237bf6424dd6f75)".

Footer nav should be all the pages about the site: About, Tags, Mod Log. Maybe Privacy if that joke isn't too tired at this point, or we're ready to make it not a joke. Chat, Stats, and Hats move into a subnav under About. The user tree is still linked from user profiles. Drop Wiki, which is only used for a list of sister sites.

And then I think that's every site page types accessible within two clicks from any page (nav -> subnav).

**Comment by pushcx** [comment]
Breakdown and details in PR #1061, but here's some WIP screenshots.

mobile nav, visitor:
![mobile-visitor](https://user-images.githubusercontent.com/6262/155037241-428c4bf2-1326-4794-872e-c553b9422320.png)

mobile nav, user:
![mobile-user](https://user-images.githubusercontent.com/6262/155037245-2dbcf071-d7fd-425c-bda6-2243f07d8cdd.png)

In the user screenshot above, if there are more items than the top-level nav can fit, it's horizonally scrollable (a comfortable interaction on mobile). The 'Login' or envelope link stays pinned to the right corner.


desktop nav, visitor:
![desktop-visitor](https://user-images.githubusercontent.com/6262/155037253-91d3644c-05c6-465e-b8e8-714f8c030814.png)

desktop nav, user:
![desktop-user](https://user-images.githubusercontent.com/6262/155037255-096f037d-8cf4-4371-b903-a8bb40f8b542.png)

**Comment by pushcx** [comment]
Here's some full-page screenshots, the PR is basically done.  

You can see the header, subnav, and footer on the homepage and an individual story. The header is the exiting bit, but there's also a hundred fiddly alignment fixes to make items line up better.

(The little tab on the left side, midway down with dimensions is Firefox UI, not a page element.)

Desktop homepage:
![Screen Shot 2022-02-27 at 15 33 50-fullpage](https://user-images.githubusercontent.com/6262/155889277-ce8896e3-071a-419a-ab6d-9ae3408a5ac2.png)

Desktop story:
![Screen Shot 2022-02-27 at 15 34 15-fullpage](https://user-images.githubusercontent.com/6262/155889282-fe9eec50-54bd-4539-8bd3-aeb08ffce225.png)

Mobile homepage:
![Screen Shot 2022-02-27 at 15 38 52-fullpage](https://user-images.githubusercontent.com/6262/155889297-da251bb5-1957-4c20-bea8-1ad5b11c8164.png)

Mobile story:
![Screen Shot 2022-02-27 at 15 38 22-fullpage](https://user-images.githubusercontent.com/6262/155889288-69bd38cb-77bd-47e8-be15-2ce38e52615b.png)

In progress:
 * Mobile dark mode header has the light mode color.
 * Still debating putting Recent back in the main nav.
 * Still debating putting Your Threads back in the user nav as just 'Threads'.

This is not much, but I will probably wait until Thursday, Friday, or Saturday to deploy. There's lower traffic those day and as many times as I've gone over the pages, I'm sure there'll be a bug or two. I appreciate contributions or ideas as I [wrap this up](https://github.com/lobsters/lobsters/issues/580#issuecomment-1028478476), leave a comment or ping me in [#lobsters](https://lobste.rs).

**Comment by pushcx** [comment]
@pjanx  The new adblock rule for karma is `lobste.rs###header nav .karma`

**Comment by pushcx** [comment]
I put Recent and Threads back in the top-level nav. Recent is useful for getting attention to upcoming stories so the homepage keeps changing. The answers I got from users of Your Threads is that they like being able to see the context of what they're replying to and, when they do get replies, which comment of _theirs_ people are replying to. This might be a nice feature for /replies, a toggle to show the parent comment.

**Comment by pushcx** [comment]
After two and a half years open for public comments, and five weeks of [announced](https://twitter.com/pushcx/status/1497964792509837314) and [re-announced](https://lobste.rs/s/ju71h0/what_are_you_doing_this_week#c_gxtm9x) public development including detailed notes and screenshots, I'm utterly certain that everyone with an opinion about this work [has already expressed it](https://github.com/lobsters/lobsters/issues/580#issuecomment-1028478476). Deploying.
