### ISSUE TITLE
TypeError TypeError: superclass must be a Class (Module given)

### ISSUE THREAD

**Issue by guillaumebriday** [lobsters/lobsters#599]
Hey ! First, thank you for your work.

I've got this error since yesterday:

```bash
TypeError: superclass must be a Class (Module given)
  /lobsters/extras/prohibit_safe_navigation.rb:14:in `<module:Style>'
  /lobsters/extras/prohibit_safe_navigation.rb:3:in `<module:Cop>'
  /lobsters/extras/prohibit_safe_navigation.rb:2:in `<module:RuboCop>'
  /lobsters/extras/prohibit_safe_navigation.rb:1:in `<top (required)>'
```

Do you know how to fix it ?

Thank you

**Comment by evexoio** [comment]
Hey, this error is due to a recent change, I think its this [commit](https://github.com/lobsters/lobsters/commit/1e5a7fc81f45588bd8c3b7441130b69d57b9cd08)

for the time being you can just rollback to a working version until a fix is pushed, I'll see if I can work on this myself.

rollback command: `git reset --hard b23f106477d6c6d464881925d2dc1a3d6d024bea`

Can you please provide reproduction steps of this error?

**Comment by guillaumebriday** [comment]
I created a repo to automatically pull the project twice a week in a docker image. Then it just start the server after a `bundle install`.

If we want to disabled the safe_navigation, could we just not disable this cop ? https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Rails/SafeNavigation

Thanks

**Comment by evexoio** [comment]
> If we want to disabled the safe_navigation, could we just not disable this cop ?

I don't get you, can you please elaborate?

I just made a clean install of lobste.rs locally, it went great. I didn't have the error.

later I ran rubocop. I din't get the error as well.

```
$ bundle exec rubocop
Inspecting 131 files
...................................................................................................................................

131 files inspected, no offenses detected
$
```

**Comment by pushcx** [comment]
The cop doesn't disable the SafeNavigation cop, it prohibits the use of the safe navigation operator; see #596 for details.

I also can't reproduce this bug, but I can guess at it. I think the `class DisallowSafeNav < Cop` is trying to reference the `Cop` module a couple lines above instead of the class `Cop` that must also be defined somewhere in the rubocop namespace. It implies to me that Rails is loading this file in production mode where rubocop is not included because it's only in the `:test, :development` groups of the `Gemfile`. I can't guess what would prompt this, though. Huh. Unless... Rails is eager-loading everything in `extras` as it starts? That's possible, but I would expect that I'd have seen issues when I deployed this code yesterday.

Maybe try adding something like `raise if Rails.env.production?` to the top of the file? That'd tell us if my guess is correct, in which case I can commit that with `return` instead of `raise` and the file will be skipped in production. (Maybe there's a cleaner solution someone can offer? I'm writing off the top of my head.)

**Comment by evexoio** [comment]
@pushcx you're right! I could reproduce the error when running in production env.

```
$ RAILS_ENV=production rails s
=> Booting WEBrick
=> Rails 5.2.1 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
Exiting
/Users/evex/dev/lobsters/extras/prohibit_safe_navigation.rb:14:in `<module:Style>': superclass must be a Class (Module given) (TypeError)
	from /Users/evex/dev/lobsters/extras/prohibit_safe_navigation.rb:3:in `<module:Cop>'
	from /Users/evex/dev/lobsters/extras/prohibit_safe_navigation.rb:2:in `<module:RuboCop>'
	from /Users/evex/dev/lobsters/extras/prohibit_safe_navigation.rb:1:in `<top (required)>'
	from /Users/evex/.rvm/gems/ruby-2.3.3/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
	from /Users/evex/.rvm/gems/ruby-2.3.3/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
	from /Users/evex/.rvm/gems/ruby-2.3.3/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
	from /Users/evex/.rvm/gems/ruby-2.3.3/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
...
```

I think a `unless Rails.env.production?` could solve it. will work on a PR.

**Comment by guillaumebriday** [comment]
Thank, you're correct, it only fails in production, I tried in development without issue !

**Comment by momolog** [comment]
Hey @evexoio , you wrote in https://github.com/lobsters/lobsters/issues/599#issuecomment-441570479 that the issue was caused by [this commit](https://github.com/lobsters/lobsters/commit/1e5a7fc81f45588bd8c3b7441130b69d57b9cd08).

I fail to understand how, can you please explain how these innocuous changes can have caused this bug? I have a similar issue I am trying to understand.
