### ISSUE TITLE
Message username autocomplete

### ISSUE THREAD

**Issue by ozturan** [lobsters/lobsters#627]
It would be amazing if the "tag autocomplete" system that is present in the "Submit Story" page is used in the @new_message form. It is hard to find the username and c/p. I would love to do that if I was a Ruby/Javascript coder. 

Best Regards,

Dogancan

**Comment by pushcx** [comment]
No one has volunteered to do this in the last six weeks, and I'm unlikely to accept a PR for it because it would require an ajax endpoint (story submission page can just include all the tags; we have 10k and counting users). That's a lot of complexity for private messaging, which is deliberately a bit under-designed to nudge people towards email.
