### ISSUE TITLE
Fetched story titles are missing apostrophes and other special characters

### ISSUE THREAD

**Issue by roryokane** [lobsters/lobsters#648]
## The problem

Recently I noticed two stories, each of whose titles on Lobsters was missing an apostrophe that was in the title of the linked page. The most recent of those stories was [Sometimes **its** better for tests to hit the real API](https://lobste.rs/s/wortjv/sometimes_its_better_for_tests_hit_real), which links to an article titled [Sometimes **it’s** better for tests to hit the real API](https://www.codewithjason.com/sometimes-better-tests-hit-real-api/). If you paste that URL in the [Submit Story](https://lobste.rs/stories/new) page and click Fetch Title, the fetched title is missing the apostrophe, so that’s probably why those stories were submitted with inaccurate titles.

The title fetched by the Fetch Title button on the Submit Story page should not omit any visible characters. There may be a security argument for omitting some characters such as the Unicode LTR character, but the apostrophe `’` (and the straight single quote `'`) should definitely be preserved.

I haven’t tested whether the button also strips other special characters that should be preserved, such as `"`.

## Investigating the cause

The Fetch Title button seems to be currently powered by this JavaScript:

https://github.com/lobsters/lobsters/blob/fdd85dbe3d05984398d019d048d812c960e79a89/app/assets/javascripts/application.js.erb#L351-L377

I don’t see any explicit escaping code in that JavaScript. Maybe jQuery does the excessive escaping, or maybe it’s an encoding issue.

I don’t see anything wrong in the Fetch Title button’s view code:

https://github.com/lobsters/lobsters/blob/fdd85dbe3d05984398d019d048d812c960e79a89/app/views/stories/_form.html.erb#L9-L10

https://github.com/lobsters/lobsters/blob/fdd85dbe3d05984398d019d048d812c960e79a89/app/views/stories/_form.html.erb#L155-L160

**Comment by briankung** [comment]
Confirmed, the site does not do well with Unicode characters. Testing with https://rain-mailman.glitch.me/ with title 你好世界！ results in an empty string.

Right now we're using `encode!([options])`, which oddly enough isn't a method signature that matches anything [in the docs for `#encode!`](https://ruby-doc.org/core-2.3.3/String.html#method-i-encode!) and we're not setting a destination encoding. I attempted to use `String#encode` with the destination encoding of `'utf-8'`, but unfortunately it returned empty string as the title, due to throwing `Encoding::UndefinedConversionError` at line 925 (https://github.com/lobsters/lobsters/blob/master/app/models/story.rb#L919-L929). `force_encoding` as in #653 seems to do the trick without raising an error.
