### ISSUE TITLE
Replies in posts that have been hidden are not shown even after the post has been unhidden

### ISSUE THREAD

**Issue by gustafe** [lobsters/lobsters#675]
I commented in a post, but I decided to hide it after the comment.

When checking my thread view, I saw an answer to my comment, and decided to unhide the post. 

Replies to my comment after unhiding the post did not appear under my "Replies" view, however.

**Comment by pushcx** [comment]
Looks like that's because unhiding a post doesn't create a `ReadRibbon`, only visiting the story page does.

**Comment by jbbarth** [comment]
I tried to look into this one: 
- the ReadRibbon should already exist since it's created when visiting a story _or_ hiding it
- but it is switched to `is_following = false` when hiding (via `ReadRibbon.hide_replies_for()`), and never gets back to `is_following = true` when unhiding
- the fix is pretty trivial, we can just have a `ReadRibbon.unhide_replies_for()` counterpart called when unhiding a story

I'll try to submit a PR with the fix in the next few days.

**Comment by pushcx** [comment]
Fixed by @jbbarth in #693.
