### ISSUE TITLE
Comment count on merged story doesn't include comments from source story

### ISSUE THREAD

**Issue by alanpost** [lobsters/lobsters#683]
This morning I merged story 5o7wvj in to qlgw0n.  After doing so and as of right now, the comment count as displayed on the home page and the story page shows a count of two (2) whereas manually counting shows three (3) comments.

I expected the comment count to be three (3) rather than two (2) to correspond to the sum of comments on both stories.

**Comment by pmueller** [comment]
It appears this happens due to `Story#update_comments_count!` not running callbacks. (https://github.com/lobsters/lobsters/blob/627b6c5df7e3e70883c54fff1595e3bf9b00c92a/app/models/story.rb#L809)
If a comment originally on story 5o7wvj was e.g deleted, it would update the comments count for 5o7wvj but not run the callback for `update_merged_into_story_comments`, so qlgw0n would be left with an incorrect comments count
