### ISSUE TITLE
use with mailgun smtp server?

### ISSUE THREAD

**Issue by chovy** [lobsters/lobsters#718]
Is it possible to setup with mailgun smtp server? I'm using the lobsters-docker project on github.

**Comment by alanpost** [comment]
Have a look at `config/initializers/email.rb` for the configuration available for your SMTP server.  In production we use a local mail queue and a sendmail frontend--that's not going to change, due to the volume of mail we send out--but I believe the answer to your question is that it is possible, you need to arrange for the correct mail server configuration in your environment.

This ticket queue is for the site itself, rather than a forum for help configurating other Lobsters instances.  If you'd like further help, feel free to stop by the #lobsters IRC channel on Freenode.  In the meantime, I'll resolve this ticket.
