### ISSUE TITLE
Attempting to edit a title fails of the resulting edit is longer than the title character limit

### ISSUE THREAD

**Issue by gustafe** [lobsters/lobsters#787]
Issue: if one edits a title (for example, to remove extranous components), the edit will fail if the resulting title is longer than the character limit:

![image](https://user-images.githubusercontent.com/8576740/69219997-521d8680-0b74-11ea-8aa9-730537808c8c.png)

To repro, try removing the text " - Scott Hanselman" from this entry: 

https://lobste.rs/stories/yjflnz

**Comment by pushcx** [comment]
This is a trivial bug, the field has a `maxlength` of 100 when the Story model has a max of `150`, so it's serving back a title too long for the client-side validation. The fix is to extract that 150 to a shared constant.

But... what is this popup and where is it coming from? The only search results I'm finding for this text are from [bouncer.js](https://github.com/cferdinandi/bouncer) which we don't use. I see some mention of it being a Chrome feature, but I see a similar view in Firefox:

![Screenshot from 2019-11-20 08-09-24](https://user-images.githubusercontent.com/6262/69246756-37add200-0ba1-11ea-8c37-4aa234ee864c.png)

Is this a new browser feature that is not well-documented? I found [an MDN doc](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation) but can't find this error in its examples.

**Comment by pushcx** [comment]
For future searchers, the error message is:

> Please shorten this text to 100 characters or less (you are currently using 111 characters).

**Comment by dreadnip** [comment]
This looks like the error from the [maxlength HTML5 form validation attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdefmaxlength), which is kind of weird because when you set that property (to let's say maxlength="100"), the field should limit your input to 100 characters. You shouldn't be able to type in it once you hit that limit.

Is this field populated from the back-end? That would be the only explanation I can think of. Anyway, take a look if there's any minlength/maxlength attributes set on that specific input.

**Comment by pushcx** [comment]
Fixed in fe0d64bc
