### ISSUE TITLE
All domain pages return 404 Not Found

### ISSUE THREAD

**Issue by skeeto** [lobsters/lobsters#812]
Every post includes a link where the text is just the domain name. However, these links all lead to 404 responses. For example:

https://lobste.rs/domain/github.com

I pulled that one right off the front page just now. I instead expect a list of (recent?) posts to that domain, which is conventionally what would appear here.

**Comment by alanpost** [comment]
Thank you for reporting this issue, @skeeto.

We're aware this slug is broken and there is work in progress to fix it.  The problem was introduced in PR #797, which was written in response to systemic, abusive traffic (spam) requests we received on or about December 27th 2019.

We mitigated the problem that day and after accelerated developed of the feature in that PR.  As our deployment of the fix had an uncharacteristic rush it has temporarily broken this feature.

I'll leave this ticket open until a fix is deployed.  Please let me know if you have any questions.

**Comment by skeeto** [comment]
Thank you for all the info!

**Comment by hmadison** [comment]
The fix is in PR #811. I'm working on getting it onto the test server this evening for validation.

**Comment by alanpost** [comment]
@skeeto, @pushcx just deployed PR #811 after @hmadison tested it earlier today.  Will you try the domain link again and confirm that it is no longer producing a 404?  If It's still broken please write back and I'll reopen this ticket.

**Comment by skeeto** [comment]
Looks great, thanks!
