### ISSUE TITLE
Display issue on mobile when story titles contains URL

### ISSUE THREAD

**Issue by shelches** [lobsters/lobsters#849]
Display issue on mobile when story titles contains URL. Please see attached screenshot.
![IMG_0933](https://user-images.githubusercontent.com/42914500/78914181-abb51d80-7a4f-11ea-8a02-e4bd30ab84f3.jpg)

**Comment by pushcx** [comment]
Looks like we'll need to add an `overflow` to a containing element. Thanks for the bug report and screenshot, it made the issue perfectly clear.

**Comment by emdemir** [comment]
Seems more like `word-break` to me. I'll try to add it.

**Comment by emdemir** [comment]
I can't reproduce this on Firefox. Maybe it's a Safari only thing?

**Comment by ebanisadr** [comment]
First time participating in this repo, so let me know if I do something wrong here.

Seems like @emdemir had the right idea with word-break, but there is a bit more complexity here.

### Current behavior
Word breaking in titles is currently happening at the view ([app/views/stories/_listdetail.html.erb](https://github.com/lobsters/lobsters/blob/master/app/views/stories/_listdetail.html.erb#L26)) level, using the helper function `break_long_words(str, len=30)` declared in [`app/helpers/application_helper.rb`](https://github.com/lobsters/lobsters/blob/master/app/helpers/application_helper.rb#L14-L22). It just so happens that the word `https://example.org/~username/` is exactly 30 characters long, and does not get split. This causes the container div to expand to fit the whole word, into the space for the comment button. On extremely narrow browsers, there may not be enough space to show 30 characters and the comment button in the same line.

Another minor oddity is that, when automatic word breaks are inserted, they are inserted in pairs, and have 30 characters between them. For example, `"https://example.com/really/long/domain/name/that/doesnt/fit/here"` turns into `"<wbr><wbr>https://example.com/really/lon<wbr><wbr>g/domain/name/that/doesnt/fit/<wbr>here"`.

This behavior is from the 2015 commit https://github.com/lobsters/lobsters/commit/168d9bfe, which predates the CSS property suggested below.

### Fix options
1. **Remove the helper and break words in browsers, my suggested option** The `break_long_words` helper function is only called from that one specific partial view, and is not used anywhere else. It causes odd behavior when used in conjunction with in-browser word breaking at small screen sizes; [see picture](https://user-images.githubusercontent.com/24218339/98843413-2b510380-2408-11eb-8e57-c4b009563070.png) (browser width ~309px to reproduce. The fragment "on" gets its own line because the word is broken by the browser after `/really/l`, `on` wraps to a new line, and the application inserted word break is used to prevent `g/domain/name/that/doesnt/fit/` from overflowing the same line. It's instead put on the next line, leading to a weird wrapping. This fix can be implemented by adding the single css property `word-break: break-word;` applied to the `ol.stories li.story div.story_liner` declaration (either [for mobile](https://github.com/lobsters/lobsters/blob/master/app/assets/stylesheets/mobile.css#L131) or [desktop](https://github.com/lobsters/lobsters/blob/master/app/assets/stylesheets/application.css#L447)). I have not tested whether this would cause other weird behavior. I doubt it would because [w3schools says about `break-word`: "to prevent overflow, word may be broken at arbitrary points"](https://www.w3schools.com/cssref/css3_pr_word-break.asp), which I interpret to mean that words will only be broken if they would otherwise overflow. That interpretation matches what I've seen by adding the property in dev tools. [Example fix](https://user-images.githubusercontent.com/24218339/98846015-bb447c80-240b-11eb-9067-b04a6dca9342.png), [compatibility](https://caniuse.com/mdn-css_properties_word-break_break-word). 

2. **Lower the default number of characters before a word is broken** 28 or so would probably do the trick. This might still leave weird wrapping behavior with extremely long words on wide browsers that is no better semantically than having browsers break words.

I'll write the PR for this soon.

**Comment by pushcx** [comment]
You fixed it by deleting code? That's wonderful!

Thanks for picking up this issue, giving it such a thorough investigation, sharing a clear writeup, and of course fixing it. I really appreciate your help.
