### ISSUE TITLE
Clickable (unread) labels

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#919]
Since 5bd669dab8f15509d50993c9832a31295d75e18e unread comments have a label reading `(unread)`, separate from the `3 hours ago` label. It'd be a nice little use of javascript if clicking an `(unread)` moved you down the page to the next unread comment. (We could do it with html anchors, but I don't want to loop the comments an extra time, comment rendering is expensive enough already.)

**Comment by johnpash** [comment]
I've added the scrolling feature as suggested. My initial attempt was using html anchors but I found that the user-experience wasn't as good as with JS. The anchors worked essentially the same way but it happened to quickly that you could miss what just happened. JS with smooth scrolling gives you time to see what's going on, but not so much that it's annoying.

I've also added "cursor: pointer" to these so that it's discoverable.

**Comment by pushcx** [comment]
Just noticed this feature request didn't get closed when the feature was merged.

**Comment by pushcx** [comment]
Also touched in #1319 just to cross-link.
