### ISSUE TITLE
https://www.lobste.rs/ reports an invalid certificate

### ISSUE THREAD

**Issue by gustafe** [lobsters/lobsters#977]
Browsing https://www.lobste.rs/ reports a certificate error:

![image](https://user-images.githubusercontent.com/8576740/109296513-b37cdc80-7830-11eb-833a-066e1d4da543.png)

This is probably because the cerficate is issued for 'lobste.rs' and excludes 'www.lobste.rs'. 

However, 'www.lobste.rs' does respond to queries (unlike for example 'ftp.lobste.rs') so it should either be covered by the certificate, or the server restricted from responding to queries to that address.

**Comment by arp242** [comment]
I noticed this as well; specifically, I ended up on "www.lobste.rs" as it's indexed like that in some search results. Don't know where those are coming from though.

**Comment by pushcx** [comment]
also tracked as https://github.com/lobsters/lobsters-ansible/issues/75

**Comment by joshklein** [comment]
An uninformed hypothesis after encountering this myself:

_Please note that I have no knowledge of the codebase or its issue history, and no personal expectation of issue resolution; I'm pitching this comment into the ether just in case someone finds it useful in the future._

1) Perhaps older server configuration settings outside the version controlled codebase previously had been on e.g. OpenBSD httpd and used a different configuration logic for 300 redirects at the time third party search engines crawled and cached pages to be served as their present results, then there could have been a change to httpd.conf logic or a hosting migration to something else that e.g. now runs nginx instead with a different set of configuration assumptions, and so on.

2) If this is the case, one could attempt a relatively quick fix by updating current configuration for request handling (wherever that happens) to use 301 Moved Permanently redirect codes for all www subdomain requests (even those never previously cached by search engines) redirect to a non-www version of the requested URL. There may be a discussion to be had about whether implementing this fix is the Right Way or Wrong Way, but I have no horse in that race. There's also "correcting it on the search engine side" with a variety of tools and concepts not part of the HTTP specification, but part of those search engines' available tools.

3) Alternatively, being a lobste.rs user myself now aware of the existence of this issue, manually removing the www subdomain from an occasional search result myself, on the rare occasion I need to find an old thread, is in the issue category one could label "easiest of all possible things I can do myself to lighten my support burden on the administrators".

4) I am at this issue page after speaking to @pushcx about receiving an SSL_ERROR_BAD_CERT_DOMAIN - since this is an error some browsers don't provide an in-browser UI option for the user to overrule the error's warning and "go back" advice, there may be the additional consideration that my lack of context meant I had to use a more creative workaround to access a page of interest because it hadn't immediately occurred to me that an incorrectly result-cached subdomain could be at issue. I initially reported what I believed to be a LetsEncrypt SSL certificate issue in a private message elsewhere (some search results link to pages with an expired cert, others with an invalid domain).  

5) This issue would be more pressing if one wanted to increase search traffic from non-users, but the public existence of this issue page and the discussion within (itself being a document on the web) may be a more immediate fix that suffices for any active lobste.rs user.

**Comment by pushcx** [comment]
@fdelapena in [chat](https://lobste.rs/chat) diagnosed and solved this issue with `certbot --expand`. The cert now covers `www.lobste.rs`, which 301s to the matching `lobste.rs` url. Some implementation detail in lobsters/lobsters-ansible#75
